engines:
  rubocop: { enabled: true  }
  fixme:   { enabled: false }
exclude_paths:
- .rubocop.yml
- .codeclimate.yml
- .travis.yml
- .gitignore
- .rspec

- Gemfile.lock
- CHANGELOG.md
- readme.md
- README.md
- Readme.md
- ReadMe.md
- COPYING
- LICENSE
- NEWS

- test/**/*
- vendor/**/*
- features/**/*
- script/**/*
- spec/**/*
ratings:
  paths:
  - lib/**/*.rb
